title: Everett Helm
email: Everetthelm3@gmail.com
description: Personal site and blog for Everett Helm.
url: "https://everetthelm.github.io"
baseurl: "/AboutMe"
lang: en

accent_image: /assets/img/sidebar-bg.jpg
accent_color: rgb(79,177,186)
theme_color: rgb(25,55,71)

remote_theme: hydecorp/hydejack

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: Everett Helm
  email: Everetthelm3@gmail.com
  social:
    email: Everetthelm3@gmail.com
    github: EverettHelm
    linkedin: https://linkedin.com/in/everett-helm-730131282

data_social:
  linkedin:
    name: LinkedIn
    icon: icon-linkedin

menu:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

hydejack:
  no_push_state: false
  no_drawer: false
  no_navbar: false

  dark_mode:
    always: false
    dynamic: true
    sunrise: 6
    sunset: 18
    icon: true

defaults:
  - scope:
      path: ""
    values:
      layout: page
