title: Everett Helm
email: you@example.com
description: Personal site and blog for Everett Helm.
url: ""
baseurl: ""
lang: en

accent_image: /assets/img/sidebar-bg.jpg
accent_color: rgb(79,177,186)
theme_color: rgb(25,55,71)

remote_theme: hydecorp/hydejack

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: Everett Helm

menu:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

hydejack:
  no_push_state: false
  no_drawer: false
  no_navbar: false

  dark_mode:
    always: false
    dynamic: true
    sunrise: 6
    sunset: 18
    icon: true

defaults:
  - scope:
      path: ""
    values:
      layout: page
